# Generated by Django 5.0.4 on 2026-04-16 19:03

import apps.models.managers
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Russian Name')),
                ('name_uz', models.CharField(blank=True, max_length=200, verbose_name='Uzbek Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, verbose_name='Russian Description')),
                ('description_uz', models.TextField(blank=True, verbose_name='Uzbek Description')),
                ('primary_body_part', models.CharField(choices=[('shoulders', 'Shoulders'), ('chest', 'Chest'), ('biceps', 'Biceps'), ('forearm', 'Forearm'), ('abs', 'Abs'), ('obliques', 'Obliques'), ('quads', 'Quadriceps'), ('adductors', 'Adductors (Inner Thigh)'), ('abductors', 'Abductors (Outer Thigh)'), ('traps', 'Trapezius'), ('triceps', 'Triceps'), ('lats', 'Latissimus Dorsi'), ('lower_back', 'Lower Back'), ('glutes', 'Glutes'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves'), ('cardio', 'Cardio')], default='shoulders', verbose_name='Muscle Group')),
                ('thumbnail', models.ImageField(upload_to='exercises/thumbnails/', verbose_name='Image')),
                ('video', models.FileField(upload_to='exercises/videos/')),
                ('calory', models.IntegerField(default=0, verbose_name='Calories')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('recommended_weight', models.FloatField(default=0, verbose_name='Recommended weight (W1)')),
                ('workout_type', models.CharField(choices=[('gym', 'Gym'), ('home', 'Home')], default='gym', max_length=10, verbose_name='Workout type')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HandbookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Kategoriya nomi')),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (EN)')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description (UZ)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description (RU)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='handbook/categories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Asosiy rasm')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='handbook/categories/icons/', verbose_name='Ikona')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('weeks_count', models.IntegerField(default=6)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('admin', 'Admin'), ('auto', 'Auto'), ('custom', 'Custom')], default='admin', max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('goal', models.CharField(choices=[('fat_loss', 'Fat loss'), ('muscle_gain', 'Muscle gain'), ('recomposition', 'Recomposition'), ('general', 'General fitness')], default='general', max_length=20)),
                ('is_template', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('workout_type', models.CharField(choices=[('gym', 'Gym'), ('home', 'Home')], default='gym', max_length=10)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='ProgressionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('sets_increment', models.IntegerField(default=0)),
                ('reps_increment', models.IntegerField(default=0)),
                ('multiplier', models.FloatField(default=1.0)),
                ('threshold', models.FloatField(default=0)),
                ('small_increment', models.FloatField(default=1.25)),
            ],
            options={
                'verbose_name': 'Progression Setting',
                'verbose_name_plural': 'Progression Settings',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('monthly', '1 oylik'), ('quarterly', '3 oylik'), ('yearly', '1 yillik')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('user', 'User')], default='user', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', apps.models.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HandbookSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Sub-kategoriya nomi')),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (EN)')),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description (UZ)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description (RU)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='handbook/subcategories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='apps.handbookcategory')),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HandbookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='Nomi')),
                ('title_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title (RU)')),
                ('title_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title (EN)')),
                ('slug', models.SlugField(blank=True, max_length=350)),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('short_description_uz', models.TextField(blank=True, max_length=500, null=True, verbose_name='Short description (UZ)')),
                ('short_description_ru', models.TextField(blank=True, max_length=500, null=True, verbose_name='Short description (RU)')),
                ('short_description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='Short description (EN)')),
                ('description', models.TextField(help_text="HTML bo'lishi mumkin")),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description (UZ)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description (RU)')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='handbook/items/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='handbook/items/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm', 'm4v'])])),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apps.handbooksubcategory')),
            ],
            options={
                'ordering': ['subcategory', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.plan',),
        ),
        migrations.AddField(
            model_name='plan',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='apps.program'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(default='User', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('fitness_goal', models.CharField(blank=True, choices=[('build_body', 'Build a great body'), ('lose_weight', 'Lose weight'), ('gain_muscle', 'Gain muscle'), ('get_shape', 'Get in shape')], max_length=20)),
                ('workout_days_per_week', models.IntegerField(blank=True, null=True)),
                ('unit_system', models.CharField(choices=[('metric', 'Metric'), ('english', 'English')], default='metric', max_length=10)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserMotivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivation', models.CharField(choices=[('healthy_lifestyle', 'I want a healthy lifestyle'), ('improve_physique', 'Improve my physique'), ('get_stronger', 'Get stronger every day'), ('good_challenge', 'I like a good challenge')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivations', to='apps.userprofile')),
            ],
            options={
                'verbose_name': 'User Motivation',
                'verbose_name_plural': 'User Motivations',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(editable=False, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='apps.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='apps.userprofile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to='apps.userprofile'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('processing', 'Jarayonda'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.IntegerField(verbose_name='Summasi')),
                ('is_auto_payment', models.BooleanField(default=False, verbose_name='Is Auto Payment')),
                ('auto_payment_attempt', models.IntegerField(default=0, verbose_name='Automatic payment attempt')),
                ('completed_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Completed Date')),
                ('created_at_ms', models.BigIntegerField(blank=True, null=True, verbose_name='Created At MS')),
                ('perform_time', models.BigIntegerField(default=0, null=True, verbose_name='Perform Time')),
                ('cancel_time', models.BigIntegerField(default=0, null=True, verbose_name='Cancel Time')),
                ('state', models.IntegerField(default=1, null=True, verbose_name='State')),
                ('payme_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='apps.subscription', verbose_name='Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='apps.userprofile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='apps.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_programs', to='apps.userprofile')),
            ],
            options={
                'verbose_name': 'Favorite Program',
                'verbose_name_plural': 'Favorite Programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='apps.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_exercises', to='apps.userprofile')),
            ],
            options={
                'verbose_name': 'Favorite Exercise',
                'verbose_name_plural': 'Favorite Exercises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Collection Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_collections', to='apps.userprofile')),
            ],
            options={
                'verbose_name': 'Favorite Collection',
                'verbose_name_plural': 'Favorite Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.IntegerField(default=10)),
                ('last_performed_weight', models.FloatField(blank=True, null=True)),
                ('recommended_weight', models.FloatField(default=0)),
                ('recommended_weight_week', models.IntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='apps.exercise')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to='apps.favoritecollection')),
                ('progression_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to='apps.progressionsetting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='apps.userprofile')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_once', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='apps.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_assignments', to='apps.userprofile')),
            ],
            options={
                'verbose_name': 'User Program',
                'verbose_name_plural': 'User Programs',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='apps.plan')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('rounds', models.IntegerField(default=1)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='apps.week')),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
                'ordering': ['day_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserWorkoutProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.IntegerField(default=1)),
                ('current_order', models.IntegerField(default=1)),
                ('is_finished', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_workout_progresses', to='apps.userprofile')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='apps.workout')),
            ],
        ),
        migrations.CreateModel(
            name='GymWorkout',
            fields=[
            ],
            options={
                'verbose_name': 'Gym Workout',
                'verbose_name_plural': 'Gym Workouts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.workout',),
        ),
        migrations.CreateModel(
            name='HomeWorkout',
            fields=[
            ],
            options={
                'verbose_name': 'Home Workout',
                'verbose_name_plural': 'Home Workouts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.workout',),
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('unfinished', 'Unfinished'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('body_part', models.CharField(max_length=100)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='apps.userprogram')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.exercise')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='apps.workoutday')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('recommended_weight', models.FloatField(blank=True, default=0, null=True)),
                ('order', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='apps.exercise')),
                ('source_week_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_weeks', to='apps.workoutexercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='apps.workout')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calories', models.FloatField(default=0)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('exercises_completed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='completed', max_length=20)),
                ('current_exercise_index', models.IntegerField(default=0)),
                ('current_set', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.userprofile')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.workout')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=1, verbose_name='Stem Number')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('text_uz', models.TextField(blank=True, verbose_name='Uzbek Text')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='apps.exercise', verbose_name='Exercise')),
            ],
            options={
                'verbose_name': 'ExerciseInstruction',
                'verbose_name_plural': 'ExerciseInstructions',
                'ordering': ['step_number'],
                'unique_together': {('exercise', 'step_number')},
            },
        ),
        migrations.AddConstraint(
            model_name='handbooksubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uq_handbook_subcategory_slug_per_category'),
        ),
        migrations.AddConstraint(
            model_name='handbookitem',
            constraint=models.UniqueConstraint(fields=('subcategory', 'slug'), name='uq_handbook_item_slug_per_subcategory'),
        ),
        migrations.CreateModel(
            name='GymPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Gym Plan',
                'verbose_name_plural': 'Gym Plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.edition',),
        ),
        migrations.CreateModel(
            name='HomePlan',
            fields=[
            ],
            options={
                'verbose_name': 'Home Plan',
                'verbose_name_plural': 'Home Plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.edition',),
        ),
        migrations.AlterUniqueTogether(
            name='usermotivation',
            unique_together={('user', 'motivation')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteprogram',
            unique_together={('user', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteexercise',
            unique_together={('user', 'exercise')},
        ),
        migrations.AlterUniqueTogether(
            name='favoritecollection',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'exercise')},
        ),
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('plan', 'week_number')},
        ),
        migrations.AlterUniqueTogether(
            name='userworkoutprogress',
            unique_together={('user', 'workout')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('program', 'order')},
        ),
    ]
