# Generated by Django 5.0.4 on 2026-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium Plan'),
        ),
    ]
