# Generated by Django 5.0.4 on 2026-04-16 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_plan_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='progression_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.progressionsetting', verbose_name='Progression Rules'),
        ),
    ]
