# Generated by Django 5.0.4 on 2026-04-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_plan_progression_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
