# Generated by Django 5.0.4 on 2026-04-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_plan_description_plan_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='apply_to_all_weeks',
            field=models.BooleanField(default=False, help_text='If checked, this workout and its exercises will be copied to weeks 2-6 automatically.', verbose_name='Apply to all 6 weeks'),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workout',
            name='description_uz',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workout',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
