# Generated by Django 5.0.4 on 2026-04-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_workout_apply_to_all_weeks_workout_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='apply_to_all_weeks',
            field=models.BooleanField(default=False, help_text='Belgilansa, ushbu kun mashqlari 2-6 haftalarga progression bilan nusxalanadi.', verbose_name='Apply to all 6 weeks'),
        ),
    ]
