# Generated by Django 5.0.4 on 2026-04-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_workout_apply_to_all_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Davomiyligi (minutda)'),
        ),
    ]
