# Generated by Django 5.0.4 on 2026-04-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_workoutexercise_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressionsetting',
            name='multiplier',
        ),
        migrations.RemoveField(
            model_name='progressionsetting',
            name='reps_increment',
        ),
        migrations.RemoveField(
            model_name='progressionsetting',
            name='sets_increment',
        ),
        migrations.RemoveField(
            model_name='progressionsetting',
            name='small_increment',
        ),
        migrations.RemoveField(
            model_name='progressionsetting',
            name='threshold',
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='rep_w2',
            field=models.IntegerField(default=0, verbose_name='Reps +/- W2'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='rep_w3',
            field=models.IntegerField(default=-1, verbose_name='Reps +/- W3'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='rep_w4',
            field=models.IntegerField(default=0, verbose_name='Reps +/- W4'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='rep_w5',
            field=models.IntegerField(default=-1, verbose_name='Reps +/- W5'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='rep_w6',
            field=models.IntegerField(default=-2, verbose_name='Reps +/- W6 (deload)'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='set_w2',
            field=models.IntegerField(default=1, verbose_name='Sets +/- W2'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='set_w3',
            field=models.IntegerField(default=1, verbose_name='Sets +/- W3'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='set_w4',
            field=models.IntegerField(default=0, verbose_name='Sets +/- W4'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='set_w5',
            field=models.IntegerField(default=0, verbose_name='Sets +/- W5'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='set_w6',
            field=models.IntegerField(default=0, verbose_name='Sets +/- W6 (deload)'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='small_boost',
            field=models.FloatField(default=5.0, verbose_name='Small weight boost (kg)'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='small_threshold',
            field=models.FloatField(default=25.0, verbose_name='Small weight threshold (kg)'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='w2_weight_mult',
            field=models.FloatField(default=1.06, verbose_name='W2 weight multiplier'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='w3_weight_mult',
            field=models.FloatField(default=1.12, verbose_name='W3 weight multiplier'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='w4_weight_mult',
            field=models.FloatField(default=1.18, verbose_name='W4 weight multiplier'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='w5_weight_mult',
            field=models.FloatField(default=1.22, verbose_name='W5 weight multiplier'),
        ),
        migrations.AddField(
            model_name='progressionsetting',
            name='w6_deload_mult',
            field=models.FloatField(default=0.85, verbose_name='W6 deload multiplier'),
        ),
    ]
