# Generated by Django 5.0.4 on 2026-04-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_progressionsetting_multiplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], max_length=20),
        ),
    ]
