# Generated by Django 5.0.4 on 2026-04-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_program_level_and_more'),
        ('apps', '0009_usercustomprogram'),
    ]

    operations = [
    ]
