# Generated by Django 5.0.4 on 2026-04-26 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0009_usercustomprogram"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomProgramProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_calories", models.FloatField(default=0)),
                ("total_duration_seconds", models.IntegerField(default=0)),
                ("exercises_completed", models.IntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to="apps.usercustomprogram",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_program_progresses",
                        to="apps.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Program Progress",
                "verbose_name_plural": "Custom Program Progress",
                "ordering": ["-created_at"],
            },
        ),
    ]
