# Generated by Django 5.0.4 on 2026-04-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_program_level_and_more'),
        ('apps', '0010_merge_20260424_1830'),
    ]

    operations = [
    ]
