# Generated by Django 5.0.4 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_merge_20260427_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_4_week',
            field=models.BooleanField(default=False, help_text='Faqat Home Plan uchun. Belgilansa, 4 hafta bilan cheklanadi.', verbose_name='4-haftalik tsikl (Home)'),
        ),
        migrations.CreateModel(
            name='HomeProgressionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('round_w2', models.IntegerField(default=0, verbose_name='Rounds +/- W2')),
                ('round_w3', models.IntegerField(default=1, verbose_name='Rounds +/- W3')),
                ('round_w4', models.IntegerField(default=0, verbose_name='Rounds +/- W4')),
                ('duration_w2', models.IntegerField(default=5, verbose_name='Duration +/- W2 (sec)')),
                ('duration_w3', models.IntegerField(default=5, verbose_name='Duration +/- W3 (sec)')),
                ('duration_w4', models.IntegerField(default=10, verbose_name='Duration +/- W4 (sec)')),
                ('rest_between_rounds', models.IntegerField(default=60, verbose_name='Rest between rounds (sec)')),
                ('rest_w2', models.IntegerField(default=55, verbose_name='Rest W2 (sec)')),
                ('rest_w3', models.IntegerField(default=50, verbose_name='Rest W3 (sec)')),
                ('rest_w4', models.IntegerField(default=45, verbose_name='Rest W4 (sec)')),
            ],
            options={
                'verbose_name': 'Home Progression Setting',
                'verbose_name_plural': 'Home Progression Settings',
            },
        ),
    ]
