# Generated by Django 5.0.4 on 2026-05-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_plan_is_4_week_homeprogressionsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymWeek',
            fields=[
            ],
            options={
                'verbose_name': 'Gym Week',
                'verbose_name_plural': 'Gym Weeks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.week',),
        ),
        migrations.CreateModel(
            name='HomeWeek',
            fields=[
            ],
            options={
                'verbose_name': 'Home Week',
                'verbose_name_plural': 'Home Weeks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.week',),
        ),
    ]
