# Generated by Django 5.0.4 on 2026-05-21 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_gymweek_homeweek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handbookitem',
            options={'ordering': ['order', 'title']},
        ),
        migrations.RemoveConstraint(
            model_name='handbookitem',
            name='uq_handbook_item_slug_per_subcategory',
        ),
        migrations.AddField(
            model_name='handbookitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_items', to='apps.handbookcategory', verbose_name="Kategoriya (to'g'ridan)"),
        ),
        migrations.AlterField(
            model_name='handbookitem',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handbookitem',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handbookitem',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='handbookitem',
            name='short_description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='handbookitem',
            name='short_description_uz',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='handbookitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apps.handbooksubcategory', verbose_name='Sub-kategoriya'),
        ),
        migrations.AlterField(
            model_name='handbookitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='handbookitem',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='handbookitem',
            name='title_uz',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddConstraint(
            model_name='handbookitem',
            constraint=models.UniqueConstraint(condition=models.Q(('subcategory__isnull', False)), fields=('subcategory', 'slug'), name='uq_handbook_item_slug_per_subcategory'),
        ),
        migrations.AddConstraint(
            model_name='handbookitem',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False), ('subcategory__isnull', True)), fields=('category', 'slug'), name='uq_handbook_item_slug_per_category'),
        ),
    ]
