# Generated by Django 5.0.4 on 2026-06-04 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_handbookitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-start_date'], 'verbose_name': 'Obuna', 'verbose_name_plural': 'Obunalar'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['order', 'price_uzs'], 'verbose_name': 'Obuna tarifi', 'verbose_name_plural': 'Obuna tariflari'},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('humo', 'Humo'), ('uzcard', 'Uzcard'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=20, null=True, verbose_name="To'lov usuli"),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='apps.subscriptionplan', verbose_name='Tarif'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Eng mashhur'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Narx (USD)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_uzs',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Narx (UZS)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_body_part',
            field=models.CharField(choices=[('shoulders', 'Shoulders'), ('chest', 'Chest'), ('biceps', 'Biceps'), ('forearm', 'Forearm'), ('abs', 'Abs'), ('obliques', 'Obliques'), ('quads', 'Quads'), ('adductors', 'Adductors'), ('abductors', 'Abductors'), ('traps', 'Traps'), ('triceps', 'Triceps'), ('lats', 'Lats'), ('lower_back', 'Lower back'), ('glutes', 'Glutes'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves'), ('cardio', 'Cardio')], default='shoulders', verbose_name='Muscle Group'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summasi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='auto_payment_attempt',
            field=models.IntegerField(default=0, verbose_name="Avto to'lov urinishi"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan sana'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_auto_payment',
            field=models.BooleanField(default=False, verbose_name="Avto to'lov"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Bajarildi'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='apps.subscription', verbose_name='Obuna'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(editable=False, verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='apps.subscriptionplan', verbose_name='Tarif'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='period',
            field=models.CharField(choices=[('monthly', '1 oylik'), ('quarterly', '3 oylik'), ('semiannual', '6 oylik'), ('yearly', '1 yillik')], max_length=20, unique=True, verbose_name='Davr'),
        ),
        migrations.AlterField(
            model_name='usermotivation',
            name='motivation',
            field=models.CharField(choices=[('healthy_lifestyle', 'I want a healthy lifestyle'), ('improve_physique', 'Improve my physique'), ('get_stronger', 'Get stronger every day'), ('good_challenge', 'I like a good challenge')], max_length=30, verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], max_length=20, verbose_name='Experience level'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('build_body', 'Build a great body'), ('lose_weight', 'Lose weight'), ('gain_muscle', 'Gain muscle'), ('get_shape', 'Get in shape')], max_length=20, verbose_name='Fitness goal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='User', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding completed'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='unit_system',
            field=models.CharField(choices=[('metric', 'Metric'), ('english', 'English')], default='metric', max_length=10, verbose_name='Unit system'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workout_days_per_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Workout days per week'),
        ),
        migrations.AlterField(
            model_name='userprogram',
            name='assigned_once',
            field=models.BooleanField(default=False, verbose_name='Assigned once'),
        ),
        migrations.AlterField(
            model_name='userprogram',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='userprogramexercise',
            name='reps',
            field=models.PositiveIntegerField(verbose_name='Reps'),
        ),
        migrations.AlterField(
            model_name='userprogramexercise',
            name='sets',
            field=models.PositiveIntegerField(verbose_name='Sets'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='body_part',
            field=models.CharField(max_length=100, verbose_name='Body part'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Completed at'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('unfinished', 'Unfinished'), ('completed', 'Completed')], default='not_started', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
