# Generated by Django 5.0.4 on 2026-06-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_payment_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualProgram',
            fields=[
            ],
            options={
                'verbose_name': 'Individual Program',
                'verbose_name_plural': 'Individual Programs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.program',),
        ),
        migrations.AddField(
            model_name='program',
            name='is_individual',
            field=models.BooleanField(default=False, help_text="Belgilansa, bu programma oddiy ro'yxatda ko'rinmaydi. Faqat yangi foydalanuvchiga tavsiya sifatida beriladi.", verbose_name='Individual (tavsiya)'),
        ),
    ]
