# Generated by Django 5.0.4 on 2026-06-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_individual_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
    ]
