# Generated by Django 5.0.4 on 2026-06-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_program_share_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeProgram',
            fields=[
            ],
            options={
                'verbose_name': 'One-time program',
                'verbose_name_plural': 'One-time programs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.program',),
        ),
        migrations.AddField(
            model_name='program',
            name='is_one_time',
            field=models.BooleanField(default=False, help_text="Belgilansa, bu programma bitta mashg'ulot sifatida ishlaydi: progress saqlanmaydi, kategoriyalarda va tavsiyada ko'rinmaydi.", verbose_name='One-time workout'),
        ),
        migrations.AddField(
            model_name='program',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ochilishlar soni'),
        ),
    ]
