# Generated by Django 5.0.4 on 2026-06-16 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_onetimeprogram_program_is_one_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='home_progression_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.homeprogressionsetting', verbose_name='Home Progression Rules'),
        ),
    ]
