# Generated by Django 5.0.4 on 2026-06-23 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_plan_home_progression_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(blank=True, max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200)),
                ('workout_type', models.CharField(choices=[('gym', 'Gym'), ('home', 'Home')], default='gym', max_length=10)),
                ('rounds', models.IntegerField(default=1, verbose_name='Rounds (home)')),
            ],
            options={
                'verbose_name': 'Pre-made day',
                'verbose_name_plural': 'Pre-made days',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DayTemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('recommended_weight', models.FloatField(blank=True, default=0, null=True)),
                ('minutes', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Davomiyligi (minutda)')),
                ('order', models.IntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='apps.daytemplate')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_template_exercises', to='apps.exercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
