# Generated by Django 5.0.4 on 2026-06-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_daytemplate_daytemplateexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='atmos_transaction_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Atmos transaction id'),
        ),
    ]
