# Generated by Django 5.0.4 on 2026-07-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_payment_atmos_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='recommended_weight',
            new_name='start_weight_beginner',
        ),
        migrations.RemoveField(
            model_name='progressionsetting',
            name='small_boost',
        ),
        migrations.RemoveField(
            model_name='progressionsetting',
            name='small_threshold',
        ),
        migrations.RemoveField(
            model_name='progressionsetting',
            name='w2_weight_mult',
        ),
        migrations.RemoveField(
            model_name='progressionsetting',
            name='w3_weight_mult',
        ),
        migrations.RemoveField(
            model_name='progressionsetting',
            name='w4_weight_mult',
        ),
        migrations.RemoveField(
            model_name='progressionsetting',
            name='w5_weight_mult',
        ),
        migrations.RemoveField(
            model_name='progressionsetting',
            name='w6_deload_mult',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('reps_based', 'Reps based'), ('time_based', 'Time based')], default='', max_length=20, verbose_name='Exercise type'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='start_time_advanced',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start time — advanced (sec)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='start_time_beginner',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start time — beginner (sec)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='start_weight_advanced',
            field=models.FloatField(blank=True, null=True, verbose_name='Start weight — advanced (kg)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weekly_time_increment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weekly time increment (sec)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weekly_weight_increment',
            field=models.FloatField(blank=True, null=True, verbose_name='Weekly weight increment (kg)'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time-based duration (sec)'),
        ),
    ]
