# Generated by Django 5.0.4 on 2026-07-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_rename_recommended_weight_exercise_start_weight_beginner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='weekly_time_increment',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weekly_weight_increment',
        ),
        migrations.AddField(
            model_name='exercise',
            name='weekly_time_increment_advanced',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weekly time increment — advanced (sec)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weekly_time_increment_beginner',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weekly time increment — beginner (sec)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weekly_weight_increment_advanced',
            field=models.FloatField(blank=True, null=True, verbose_name='Weekly weight increment — advanced (kg)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weekly_weight_increment_beginner',
            field=models.FloatField(blank=True, null=True, verbose_name='Weekly weight increment — beginner (kg)'),
        ),
    ]
