# Generated by Django 5.0.4 on 2026-07-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_remove_exercise_weekly_time_increment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='beginner', help_text='Which exercise values this plan uses: beginner or advanced.', max_length=20, verbose_name='Difficulty'),
        ),
    ]
