# Generated by Django 5.0.4 on 2026-07-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_plan_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
    ]
