# Generated by Django 5.0.4 on 2026-07-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_plan_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='is_weight_manual',
            field=models.BooleanField(default=False, verbose_name='Manual weight/time'),
        ),
    ]
