# Generated by Django 5.0.4 on 2026-07-20 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_workoutexercise_is_weight_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_gift',
            field=models.BooleanField(default=False, verbose_name="Sovg'a to'lovi"),
        ),
        migrations.CreateModel(
            name='PremiumGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Kod')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('available', 'Faol'), ('claimed', 'Olingan')], default='pending', max_length=20, verbose_name='Status')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Olingan sana')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_payments', to='apps.payment', verbose_name="To'lov")),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts', to='apps.subscriptionplan', verbose_name='Tarif')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_gifts', to='apps.userprofile', verbose_name='Qabul qiluvchi')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_gift', to='apps.userprofile', verbose_name='Yuboruvchi')),
            ],
            options={
                'verbose_name': "Premium sovg'a",
                'verbose_name_plural': "Premium sovg'alar",
            },
        ),
    ]
