# Generated by Django 5.0.4 on 2026-07-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_payment_is_gift_premiumgift'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Xabar')),
                ('is_from_admin', models.BooleanField(default=False, verbose_name='Admindan')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='apps.userprofile', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Chat xabari',
                'verbose_name_plural': 'Chat',
                'ordering': ['created_at'],
            },
        ),
    ]
