# Generated by Django 5.0.4 on 2026-07-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='support/images/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='support/thumbnails/', verbose_name='Nusxa'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Xabar'),
        ),
    ]
