# Generated by Django 5.0.4 on 2026-07-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_supportmessage_image_supportmessage_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan sana'),
        ),
    ]
