# Generated by Django 5.0.4 on 2026-07-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_subscription_canceled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_cardio',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks this exercise as cardio. Used for auto-inserting a warm-up and for cardio-specific presentation. Independent of muscle group.', verbose_name='Cardio'),
        ),
    ]
