# Generated by Django 5.0.4 on 2026-07-26 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_backfill_is_cardio'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='auto_cardio_blocks_completion',
            field=models.BooleanField(default=False, help_text='If enabled, a training day only counts as complete when the cardio entry is done. Off by default: cardio is treated as a warm-up.', verbose_name='Cardio required to complete a day'),
        ),
        migrations.AddField(
            model_name='program',
            name='auto_cardio_duration_seconds',
            field=models.PositiveIntegerField(default=600, help_text='Duration of each cardio set, in seconds.', verbose_name='Cardio duration (sec)'),
        ),
        migrations.AddField(
            model_name='program',
            name='auto_cardio_enabled',
            field=models.BooleanField(default=False, help_text='Insert a cardio exercise as the first exercise of every training day.', verbose_name='Auto cardio'),
        ),
        migrations.AddField(
            model_name='program',
            name='auto_cardio_exercise',
            field=models.ForeignKey(blank=True, help_text='Which cardio exercise to insert. Only exercises marked as cardio are listed.', limit_choices_to={'is_cardio': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_cardio_programs', to='apps.exercise', verbose_name='Cardio exercise'),
        ),
        migrations.AddField(
            model_name='program',
            name='auto_cardio_sets',
            field=models.PositiveIntegerField(default=1, help_text='Use more than one set for interval-style cardio.', verbose_name='Cardio sets'),
        ),
        migrations.AddField(
            model_name='workout',
            name='cardio_removed',
            field=models.BooleanField(default=False, help_text="Set when an admin deletes this day's auto-inserted cardio entry. Regeneration will not restore it while this is set.", verbose_name='Cardio removed'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='is_auto_cardio',
            field=models.BooleanField(default=False, verbose_name='Auto-inserted cardio'),
        ),
    ]
