# Generated by Django 5.0.4 on 2026-07-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_auto_cardio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Trial started at'),
        ),
    ]
