# Generated by Django 5.0.4 on 2026-07-28 17:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_backfill_trial_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Latin letters and digits only. Case does not matter when entering.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'The code may contain only Latin letters A-Z and digits 0-9.')], verbose_name='Promo kod')),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Chegirma (%)')),
                ('owner_label', models.CharField(blank=True, max_length=120, verbose_name='Egasi (trener/sotuvchi)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited.', null=True, verbose_name='Maksimal ishlatilish soni')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
            ],
            options={
                'verbose_name': 'Promo kod',
                'verbose_name_plural': 'Promo kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Asl narx')),
                ('discount_amount_applied', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Chegirma summasi')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Yakuniy narx')),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ishlatilgan sana')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemptions', to='apps.payment', verbose_name="To'lov")),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='apps.promocode', verbose_name='Promo kod')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemptions', to='apps.subscription', verbose_name='Obuna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to='apps.userprofile', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Promo kod ishlatilishi',
                'verbose_name_plural': 'Promo kod ishlatilishlari',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='promoredemption',
            constraint=models.UniqueConstraint(fields=('user',), name='uniq_promo_redemption_per_user'),
        ),
    ]
