# Generated by Django 5.0.4 on 2026-07-28 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_promocode_promoredemption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Chegirmasiz summa'),
        ),
        migrations.AddField(
            model_name='payment',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='apps.promocode', verbose_name='Promo kod'),
        ),
    ]
