# Generated by Django 5.0.4 on 2026-07-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_payment_original_amount_payment_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trial_reminder_sent_day',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Last trial reminder (days left)'),
        ),
    ]
