# Generated by Django 5.0.4 on 2026-07-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_userprofile_trial_reminder_sent_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('uz', 'O‘zbekcha'), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5, verbose_name='Language'),
        ),
    ]
