name: Deploy Fitness App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚀 Deploy to Serverr
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/fitness
            git fetch --all
            git reset --hard origin/main
            source venv/bin/activate
            # Fayl nomingiz requirements.txt bo'lsa shuni yozing
            pip install -r req.txt 
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            echo "✅ Hammasi muvaffaqiyatli yakunlandi!"